// Generated by CoffeeScript 1.7.1
var app, parseMoney;

parseMoney = function(moneyStr) {
  return parseFloat(moneyStr.replace(/[\$,\,]/g, ""));
};

app = angular.module('app', []);

app.controller('appCtrl', function($scope, $http) {
  return $scope.getData = function() {
    return $http.get('data/inventory_data.json').success(function(data) {
      var arr, dt;
      dt = _(data);
      arr = [];
      data.forEach(function(e) {
        var els, f;
        f = _.find(arr, {
          department: e.department
        });
        if (f != null) {
          f.inStockCount += e.inStockCount;
          f.toDateSpent += parseMoney(e.toDateSpent);
          if (f.elements != null) {
            return f.elements.push(e);
          }
        } else {
          els = [];
          els.push(e);
          return arr.push({
            department: e.department,
            inStockCount: e.inStockCount,
            toDateSpent: parseMoney(e.toDateSpent),
            elements: els
          });
        }
      });
      $scope.departmentsData = arr;
      return $scope.selectItem = function(item) {
        return $scope.currentItem = item;
      };
    });
  };
});

app.directive('invItem', function() {
  return {
    restrict: 'E',
    scope: {
      i: '=item',
      all: '=data'
    },
    templateUrl: "item.html",
    link: function(scope) {
      scope.addItem = function(i) {
        var f;
        i.inStockCount += 1;
        f = _.find(scope.all, {
          department: i.department
        });
        f.inStockCount += 1;
        return f.toDateSpent += parseMoney(i.costPerUnit);
      };
      return scope.subtractItem = function(i) {
        var f;
        f = _.find(scope.all, {
          department: i.department
        });
        if (i.inStockCount > 1) {
          i.inStockCount -= 1;
          f.inStockCount -= 1;
          return f.toDateSpent -= parseMoney(i.costPerUnit);
        }
      };
    }
  };
});

//# sourceMappingURL=appCtrl.map
