// Generated by CoffeeScript 1.7.1
var app, express, path, rootDir;

express = require('express');

path = require('path');

app = express();

rootDir = path.resolve(__dirname, "..");

app.use(express["static"](rootDir));

app.get("/", function(req, res) {
  return res.render(rootDir + '/index.html');
});

app.listen(3000);

console.log("running localhost on port 3000");

//# sourceMappingURL=server.map
